package envíapack;

/**
 *
 * @author melic
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form frmMenu
     */
    private ListaPaquete lista;
    private PilaPaquete pila;
    private ColaPaquete cola;
    private ListaGuia listaGuias;
    private ListaDobleGuia listaDistribucion;
    
    public Menu() {
        initComponents();
        lista = new ListaPaquete();
        pila = new PilaPaquete();
        cola = new ColaPaquete();
        listaGuias = new ListaGuia();
        listaDistribucion = new ListaDobleGuia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnVerApilados = new javax.swing.JButton();
        btnApilar = new javax.swing.JButton();
        btnPaquetesACola = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnVerCola = new javax.swing.JButton();
        btnDesencolar = new javax.swing.JButton();
        btnGuia = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EnvíaPack");

        btnRegistro.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Registrar ingreso de paquete");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnVerApilados.setBackground(new java.awt.Color(0, 51, 153));
        btnVerApilados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerApilados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerApilados.setText("Ver paquetes apilados");
        btnVerApilados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerApiladosActionPerformed(evt);
            }
        });

        btnApilar.setBackground(new java.awt.Color(0, 51, 153));
        btnApilar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApilar.setForeground(new java.awt.Color(255, 255, 255));
        btnApilar.setText("Apilar paquete");
        btnApilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApilarActionPerformed(evt);
            }
        });

        btnPaquetesACola.setBackground(new java.awt.Color(0, 51, 153));
        btnPaquetesACola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPaquetesACola.setForeground(new java.awt.Color(255, 255, 255));
        btnPaquetesACola.setText("Trasladar paquetes a Cola");
        btnPaquetesACola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaquetesAColaActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(204, 0, 51));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnVerCola.setBackground(new java.awt.Color(0, 51, 153));
        btnVerCola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerCola.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCola.setText("Ver paquetes en cola");
        btnVerCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerColaActionPerformed(evt);
            }
        });

        btnDesencolar.setBackground(new java.awt.Color(0, 51, 153));
        btnDesencolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDesencolar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesencolar.setText("Desencolar paquetes");
        btnDesencolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencolarActionPerformed(evt);
            }
        });

        btnGuia.setBackground(new java.awt.Color(0, 51, 153));
        btnGuia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuia.setForeground(new java.awt.Color(255, 255, 255));
        btnGuia.setText("Generar guías de envío");
        btnGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaActionPerformed(evt);
            }
        });

        btnAsignar.setBackground(new java.awt.Color(0, 51, 153));
        btnAsignar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setText("Asignar fecha y destino");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPaquetesACola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerApilados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesencolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerApilados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnApilar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPaquetesACola, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerCola, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDesencolar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        RegistroPaquete frm = new RegistroPaquete(lista, this);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnVerApiladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerApiladosActionPerformed
        VerPaquetes frm = new VerPaquetes(pila, this);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerApiladosActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        AsignarDestino frm = new AsignarDestino();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnApilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApilarActionPerformed
        ApilarPaquete frm = new ApilarPaquete(lista, pila, this);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnApilarActionPerformed

    private void btnPaquetesAColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaquetesAColaActionPerformed
        TransladarACola frm = new TransladarACola(pila, cola, this);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnPaquetesAColaActionPerformed

    private void btnVerColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerColaActionPerformed
        VerPaquetesEnCola frm = new VerPaquetesEnCola(cola, this);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerColaActionPerformed

    private void btnDesencolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencolarActionPerformed
        DesencolarPaquete frm = new DesencolarPaquete();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnDesencolarActionPerformed

    private void btnGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaActionPerformed
        GenerarGuías frm = new GenerarGuías();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnGuiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnApilar;
    public javax.swing.JButton btnAsignar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnDesencolar;
    public javax.swing.JButton btnGuia;
    public javax.swing.JButton btnPaquetesACola;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JButton btnVerApilados;
    public javax.swing.JButton btnVerCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
